<h5>URL Assignment: https://colab.research.google.com/drive/1T9HAtxKs9LS7xXHb0OmFNWbDOf1an6RG?usp=sharing#scrollTo=VuVSlxaZDqsj</h5>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

<h1>Text Preprocessing</h1>

<h5>Lowercasing</h5>

In [5]:
df['review']=df['review'].str.lower()

In [6]:
import re
def remove_html(review):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',review)

<h5>Removing HTML tags</h5>

In [7]:
df['review']=df['review'].apply(remove_html)

In [8]:
df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

<h5>Handling Contractions</h5>

In [9]:
import sys
!{sys.executable} -m pip install contractions

Requirement already satisfied: contractions in c:\users\souha\anaconda3\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\souha\anaconda3\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\souha\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in c:\users\souha\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (2.3.1)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souha\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souha\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souha\anaconda3\Lib\site-packages)

In [10]:
import contractions
def expand_contractions(text):
    return contractions.fix(text)

In [11]:
text = "I don't think this movie is good. Who'll watch it?"
print(expand_contractions(text))

I do not think this movie is good. Who will watch it?

In [12]:
df['review']=df['review'].apply(expand_contractions)

In [13]:
df['review'][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. them city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows would not dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz does not mess around. the first episode i ever saw struck me as so nasty it was surreal, i could not say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who will be sold out for a nickel, inmates who will kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....that is if you can get in touch with your darker side.'

<h5>Removing Punctuations</h5>

In [14]:
import string
exclude=string.punctuation

def remove_punc(review):
    return review.translate(str.maketrans(exclude," " * len(exclude)))

#removing puncs and adding spaces in place of them.

In [15]:
df['review']=df['review'].apply(remove_punc)

In [16]:
df['review'][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked  they are right  as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence  which set in right from the word go  trust me  this is not a show for the faint hearted or timid  this show pulls no punches with regards to drugs  sex or violence  its is hardcore  in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  them city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows would not dare  forget pretty pictures painted for mainstream audiences  forget charm  forget romance   oz does not mess around  the first episode i ever saw struck me as so nasty it was surreal  i could not say i was ready for it  but as i watched more  i developed a taste for oz  and got accustomed to the high levels of graphic violence  not just violence  but injustice  crooked guards who will be sold out for a nickel  inmates who will kill on order and get away with it  well mannered  middle class inmates being turned into prison bitches due to their lack of street skills or prison experience  watching oz  you may become comfortable with what is uncomfortable viewing    that is if you can get in touch with your darker side '

<h5>Removing Extra Spaces</h5>

In [17]:
def remove_extra_spaces(text):
    return " ".join(text.split())

In [18]:
df['review']=df['review'].apply(remove_extra_spaces)

In [19]:
df['review'][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked they are right as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda them city is home to many aryans muslims gangstas latinos christians italians irish and more so scuffles death stares dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows would not dare forget pretty pictures painted for mainstream audiences forget charm forget romance oz does not mess around the first episode i ever saw struck me as so nasty it was surreal i could not say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards who will be sold out for a nickel inmates who will kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewing that is if you can get in touch with your darker side'

<h5>Stopword Removal</h5>

In [20]:
import nltk
from nltk.corpus import stopwords

In [21]:
def remove_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in stopwords.words("english"):
            new_text.append(" ")
        else:
            new_text.append(word)
    x=new_text[:]
    new_text.clear()
    return " ".join(x)

In [22]:
df['review']=df['review'].apply(remove_stopwords)

In [23]:
df['review'][0]

'one       reviewers   mentioned     watching   1 oz episode       hooked     right       exactly   happened       first thing   struck     oz     brutality   unflinching scenes   violence   set   right     word go trust           show     faint hearted   timid   show pulls   punches   regards   drugs sex   violence     hardcore     classic use     word     called oz         nickname given     oswald maximum security state penitentary   focuses mainly   emerald city   experimental section     prison       cells   glass fronts   face inwards   privacy     high     agenda   city   home   many aryans muslims gangstas latinos christians italians irish       scuffles death stares dodgy dealings   shady agreements   never far away   would say   main appeal     show   due     fact     goes     shows would   dare forget pretty pictures painted   mainstream audiences forget charm forget romance oz     mess around   first episode   ever saw struck       nasty     surreal   could   say     ready           watched     developed   taste   oz   got accustomed     high levels   graphic violence     violence   injustice crooked guards       sold       nickel inmates     kill   order   get away     well mannered middle class inmates   turned   prison bitches due     lack   street skills   prison experience watching oz   may become comfortable       uncomfortable viewing           get   touch     darker side'

In [24]:
df['review']=df['review'].apply(remove_extra_spaces)

<h5>Tokenization</h5>

In [27]:
from nltk.tokenize import word_tokenize

In [28]:
def tokenize(text):
    return word_tokenize(text)

In [29]:
df['review']=df['review'].apply(tokenize)

In [30]:
df['review'][0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'go',
 'trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'hardcore',
 'classic',
 'use',
 'word',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 'focuses',
 'mainly',
 'emerald',
 'city',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'city',
 'home',
 'many',
 'aryans',
 'muslims',
 'gangstas',
 'latinos',
 'christians',
 'italians',
 'irish',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'away',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'would',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romance',
 'oz',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'could',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'sold',
 'nickel',
 'inmates',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewing',
 'get',
 'touch',
 'darker',
 'side']

<h5>Lemmatization</h5>

In [20]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [21]:
def lemmatize_text(text):
    return " ".join(
        lemmatizer.lemmatize(word,pos="v")
        for word in text
    )

In [ ]:
df['review']=df['review'].apply(lemmatize_text)

In [3]:
df['review'][0]

'one reviewers mention watch 1 oz episode hook right exactly happen first thing strike oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use word call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cells glass front face inwards privacy high agenda city home many aryans muslims gangstas latinos christians italians irish scuffle death star dodgy dealings shady agreements never far away would say main appeal show due fact go show would dare forget pretty picture paint mainstream audiences forget charm forget romance oz mess around first episode ever saw strike nasty surreal could say ready watch develop taste oz get accustom high level graphic violence violence injustice crook guard sell nickel inmates kill order get away well mannered middle class inmates turn prison bitch due lack street skills prison experience watch oz may become comfortable uncomfortable view get touch darker side'

<h2>Problem- 2</h2>

<h5>Total number of words</h5>

In [36]:
total_words=sum(len(review) for review in df['review'])
print("Total words in corpus:", total_words)

Total words in corpus: 39297350

<h5>Unique words (Vocabulary)</h5>

In [37]:
vocabulary=set()

for review in df['review']:
    vocabulary.update(review)

print("Vocabulary Size:",len(vocabulary))

Vocabulary Size: 127

In [42]:
#saving the df, so i can continue from here later on.
df.to_pickle("imdb_preprocessed.pkl")

In [2]:
df=pd.read_pickle("imdb_preprocessed.pkl")

<h2>Problem- 3</h2>

<h5>Applying One Hot Encoding (OHE)</h5>

In [4]:
ohe=pd.get_dummies(df['sentiment'],dtype=int)
df=pd.concat([df,ohe],axis=1)

In [5]:
df.sample(5)

,review,sentiment,negative,positive
8542,eye labyrinth average giallo honest really sur...,positive,0,1
6805,think unfortunate lead comment movie include w...,positive,0,1
5882,scold scorn fellow christians state disappoint...,negative,1,0
48648,first f117 high tech fighter aircraft secondly...,negative,1,0
6845,quite possibly one greatest waste celluloid pa...,negative,1,0

<h2>Problem- 4</h2>

<h5>Applying Bag of Words</h5>

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [7]:
bow=cv.fit_transform(df['review'])

In [9]:
print(cv.vocabulary_)

{'one': 57917, 'reviewers': 67475, 'mention': 51733, 'watch': 87657, 'oz': 59080, 'episode': 26592, 'hook': 38060, 'right': 67811, 'exactly': 27376, 'happen': 35832, 'first': 29619, 'thing': 80522, 'strike': 76984, 'brutality': 11925, 'unflinching': 84340, 'scenes': 70374, 'violence': 86688, 'set': 71766, 'word': 89368, 'go': 33373, 'trust': 82803, 'show': 72754, 'faint': 28143, 'hearted': 36476, 'timid': 81066, 'pull': 64395, 'punch': 64434, 'regard': 66446, 'drug': 24280, 'sex': 71851, 'hardcore': 35884, 'classic': 16003, 'use': 85455, 'call': 12904, 'nickname': 56071, 'give': 33109, 'oswald': 58527, 'maximum': 50734, 'security': 71197, 'state': 76169, 'penitentary': 60490, 'focus': 30184, 'mainly': 49306, 'emerald': 25935, 'city': 15879, 'experimental': 27674, 'section': 71181, 'prison': 63564, 'cells': 14233, 'glass': 33176, 'front': 31223, 'face': 28033, 'inwards': 41321, 'privacy': 63580, 'high': 37236, 'agenda': 2859, 'home': 37870, 'many': 49902, 'aryans': 5871, 'muslims': 54720, 'gangstas': 31931, 'latinos': 46133, 'christians': 15489, 'italians': 41673, 'irish': 41404, 'scuffle': 70977, 'death': 20613, 'star': 76064, 'dodgy': 23363, 'dealings': 20584, 'shady': 71968, 'agreements': 2957, 'never': 55868, 'far': 28408, 'away': 6821, 'would': 89504, 'say': 70180, 'main': 49293, 'appeal': 5127, 'due': 24440, 'fact': 28074, 'dare': 20270, 'forget': 30465, 'pretty': 63435, 'picture': 61434, 'paint': 59263, 'mainstream': 49316, 'audiences': 6468, 'charm': 14724, 'romance': 68397, 'mess': 51914, 'around': 5675, 'ever': 27230, 'saw': 70153, 'nasty': 55294, 'surreal': 78105, 'could': 18530, 'ready': 65871, 'develop': 21953, 'taste': 79289, 'get': 32664, 'accustom': 2088, 'level': 46908, 'graphic': 34146, 'injustice': 40546, 'crook': 19241, 'guard': 34752, 'sell': 71377, 'nickel': 56054, 'inmates': 40568, 'kill': 44281, 'order': 58256, 'well': 88026, 'mannered': 49814, 'middle': 52231, 'class': 16001, 'turn': 83086, 'bitch': 9632, 'lack': 45553, 'street': 76912, 'skills': 73617, 'experience': 27669, 'may': 50742, 'become': 8392, 'comfortable': 16934, 'uncomfortable': 83877, 'view': 86507, 'touch': 81805, 'darker': 20288, 'side': 73009, 'wonderful': 89225, 'little': 47553, 'production': 63703, 'film': 29327, 'technique': 79527, 'unassuming': 83726, 'old': 57774, 'time': 81011, 'bbc': 8188, 'fashion': 28546, 'comfort': 16933, 'sometimes': 74719, 'discomforting': 22736, 'sense': 71508, 'realism': 65894, 'entire': 26453, 'piece': 61457, 'actors': 2261, 'extremely': 27897, 'choose': 15393, 'michael': 52137, 'sheen': 72268, 'polari': 62310, 'voice': 86957, 'pat': 59964, 'truly': 82781, 'see': 71231, 'seamless': 71056, 'edit': 25202, 'guide': 34834, 'reference': 66367, 'williams': 88745, 'diary': 22190, 'entries': 26492, 'worth': 89484, 'terrificly': 79962, 'write': 89594, 'perform': 60653, 'masterful': 50452, 'great': 34260, 'master': 50445, 'comedy': 16909, 'life': 47107, 'really': 65916, 'come': 16895, 'things': 80532, 'fantasy': 28390, 'rather': 65667, 'traditional': 81996, 'dream': 24107, 'techniques': 79528, 'remain': 66721, 'solid': 74620, 'disappear': 22662, 'play': 61946, 'knowledge': 44773, 'particularly': 59829, 'concern': 17336, 'orton': 58442, 'halliwell': 35532, 'flat': 29826, 'murals': 54611, 'decorate': 20807, 'every': 27267, 'surface': 78056, 'terribly': 79955, 'do': 23267, 'think': 80536, 'way': 87774, 'spend': 75336, 'hot': 38317, 'summer': 77675, 'weekend': 87904, 'sit': 73457, 'air': 3092, 'condition': 17416, 'theater': 80211, 'light': 47154, 'plot': 62090, 'simplistic': 73268, 'dialogue': 22145, 'witty': 89088, 'character': 14628, 'likable': 47193, 'even': 27204, 'bread': 11315, 'suspect': 78173, 'serial': 71686, 'killer': 44293, 'disappoint': 22666, 'realize': 65908, 'match': 50507, 'point': 62252, 'risk': 67955, 'addiction': 2352, 'proof': 63870, 'woody': 89303, 'allen': 3561, 'still': 76534, 'fully': 31391, 'control': 17980, 'style': 77214, 'us': 85438, 'grow': 34633, 'love': 48218, 'laugh': 46180, 'comedies': 16906, 'years': 90058, 'decade': 20697, 'impress': 39713, 'scarlet': 70308, 'johanson': 42697, 'manage': 49619, 'tone': 81516, 'sexy': 71897, 'image': 39422, 'jump': 43058, 'average': 6735, 'spirit': 75459, 'young': 90298, 'woman': 89198, 'crown': 19314, 'jewel': 42463, 'career': 13442, 'wittier': 89081, 'devil': 21992, 'wear': 87832, 'prada': 63026, 'interest': 40968, 'superman': 77880, 'friends': 31115, 'basically': 7956, 'family': 28290, 'boy': 11057, 'jake': 41971, 'zombie': 90871, 'closet': 16300, 'parent': 59686, 'fight': 29265, 'movie': 54174, 'slower': 73989, 'soap': 74411, 'opera': 58086, 'suddenly': 77508, 'decide': 20755, 'rambo': 65417, 'ok': 57710, 'make': 49372, 'must': 54738, 'thriller': 80735, 'drama': 24030, 'watchable': 87660, 'divorce': 23199, 'argue': 5492, 'like': 47195, 'real': 65884, 'totally': 81779, 'ruin': 68953, 'expect': 27636, 'boogeyman': 10636, 'similar': 73218, 'instead': 40781, 'meaningless': 51222, 'spot': 75658, '10': 59, 'descent': 21684, 'dialogs': 22144, 'shots': 72731, 'ignore': 39282, 'petter': 60984, 'mattei': 50621, 'money': 53432, 'visually': 86824, 'stun': 77149, 'mr': 54282, 'offer': 57573, 'vivid': 86886, 'portrait': 62740, 'human': 38638, 'relations': 66643, 'seem': 71252, 'tell': 79699, 'power': 62966, 'success': 77448, 'people': 60552, 'different': 22319, 'situations': 73481, 'encounter': 26136, 'variation': 85879, 'arthur': 5795, 'schnitzler': 70571, 'theme': 80303, 'director': 22603, 'transfer': 82122, 'action': 2233, 'present': 63344, 'new': 55889, 'york': 90251, 'meet': 51406, 'connect': 17594, 'another': 4713, 'next': 55981, 'person': 60803, 'know': 44764, 'previous': 63457, 'contact': 17823, 'stylishly': 77221, 'sophisticate': 74855, 'luxurious': 48639, 'look': 47974, 'take': 78915, 'live': 47572, 'world': 89434, 'habitat': 35261, 'souls': 74986, 'stag': 75904, 'loneliness': 47907, 'inhabit': 40484, 'big': 9332, 'best': 9067, 'place': 61809, 'find': 29467, 'sincere': 73304, 'fulfillment': 31372, 'discern': 22707, 'case': 13754, 'act': 2216, 'good': 33663, 'direction': 22593, 'steve': 76464, 'buscemi': 12424, 'rosario': 68558, 'dawson': 20483, 'carol': 13590, 'kane': 43427, 'imperioli': 39614, 'adrian': 2544, 'grenier': 34375, 'rest': 67262, 'talented': 78961, 'cast': 13823, 'alive': 3519, 'wish': 88986, 'luck': 48388, 'await': 6807, 'anxiously': 4930, 'work': 89389, 'probably': 63625, 'favorite': 28672, 'story': 76739, 'selflessness': 71368, 'sacrifice': 69302, 'dedication': 20838, 'noble': 56406, 'preachy': 63093, 'bore': 10780, 'despite': 21794, '15': 307, 'last': 46078, '25': 871, 'paul': 60100, 'lukas': 48462, 'performance': 60656, 'bring': 11594, 'tear': 79484, 'eye': 27931, 'bette': 9119, 'davis': 20459, 'sympathetic': 78580, 'roles': 68352, 'delight': 21177, 'kid': 44185, 'grandma': 34101, 'dress': 24169, 'midgets': 52250, 'children': 15198, 'fun': 31410, 'mother': 54035, 'slow': 73985, 'awaken': 6810, 'roof': 68483, 'believable': 8656, 'startle': 76153, 'dozen': 23964, 'thumb': 80807, 'sure': 78042, 'resurrection': 67306, 'date': 20393, 'seahunt': 71045, 'series': 71692, 'tech': 79508, 'today': 81314, 'back': 7074, 'excitement': 27457, 'black': 9709, 'white': 88415, 'tv': 83181, 'gunsmoke': 35024, 'hero': 36993, 'week': 87901, 'vote': 87071, 'comeback': 16896, 'sea': 71018, 'hunt': 38768, 'need': 55590, 'change': 14555, 'pace': 59132, 'water': 87690, 'adventure': 2590, 'oh': 57659, 'thank': 80146, 'outlet': 58685, 'viewpoints': 86519, 'movies': 54217, 'ole': 57800, 'believe': 8659, 'want': 87474, 'nice': 56025, 'read': 65855, 'plus': 62150, 'rhyme': 67629, 'line': 47340, 'let': 46853, 'submit': 77324, 'leave': 46441, 'doubt': 23852, 'quit': 65020, 'amaze': 3913, 'fresh': 31044, 'innovative': 40612, 'idea': 39136, '70': 1385, 'brilliant': 11573, 'drop': 24247, '1990': 648, 'funny': 31473, 'anymore': 4944, 'continue': 17910, 'decline': 20788, 'complete': 17177, 'waste': 87637, 'disgraceful': 22830, 'fall': 28221, 'painfully': 59255, 'bad': 7156, 'performances': 60657, 'almost': 3679, 'mildly': 52402, 'entertain': 26422, 'respite': 67233, 'guest': 34809, 'host': 38305, 'hard': 35875, 'creator': 18953, 'hand': 35670, 'select': 71350, 'original': 58349, 'also': 3748, 'band': 7535, 'hack': 35277, 'follow': 30253, 'recognize': 66109, 'brilliance': 11571, 'fit': 29676, 'replace': 66977, 'mediocrity': 51352, 'felt': 28908, 'respect': 67217, 'huge': 38581, 'awful': 6837, 'can': 13094, 'not': 56753, 'encourage': 26139, 'positive': 62787, 'comment': 16990, 'forward': 30600, 'mistake': 52989, '950': 1546, 'worst': 89481, 'storyline': 76754, 'soundtrack': 75012, 'song': 74773, 'lame': 45748, 'country': 18599, 'tune': 83001, 'less': 46837, 'four': 30654, 'cheap': 14834, 'extreme': 27893, 'rarely': 65602, 'happy': 35851, 'end': 26158, 'credit': 18972, 'prevent': 63448, 'score': 70785, 'harvey': 36088, 'keitel': 43874, 'least': 46422, 'bite': 9639, 'effort': 25345, 'obsessives': 57329, 'gut': 35079, 'wrench': 89559, 'laughter': 46196, 'hell': 36725, 'mom': 53365, 'camp': 13048, 'phil': 61144, 'alien': 3482, 'quirky': 65013, 'humour': 38709, 'base': 7923, 'oddness': 57480, 'everything': 27280, 'actual': 2271, 'punchlines': 64440, 'odd': 57470, 'progress': 63780, 'joke': 42738, 'low': 48265, 'budget': 12056, 'problem': 63641, 'eventually': 27226, 'lose': 48099, 'imagine': 39439, 'stoner': 76669, 'currently': 19658, 'partake': 59799, 'something': 74714, 'better': 9120, 'try': 82821, 'brother': 11810, 'planet': 61860, '12': 219, 'recall': 66030, 'scariest': 70301, 'scene': 70364, 'bird': 9553, 'eat': 25016, 'men': 51639, 'dangle': 20182, 'helplessly': 36790, 'parachute': 59576, 'horror': 38223, 'cheesy': 14937, 'saturday': 70056, 'afternoons': 2815, 'tire': 81154, 'formula': 30519, 'monster': 53570, 'type': 83327, 'usually': 85490, 'include': 39926, 'beautiful': 8334, 'might': 52308, 'daughter': 20413, 'professor': 63732, 'resolution': 67194, 'die': 22282, 'care': 13437, 'much': 54338, 'romantic': 68411, 'angle': 4506, 'year': 90049, 'predictable': 63175, 'unintentional': 84555, 'humor': 38701, 'later': 46105, 'psycho': 64218, 'janet': 42037, 'leigh': 46621, 'bump': 12226, 'early': 24937, 'notice': 56790, 'since': 73303, 'screenwriters': 70896, 'scary': 70323, 'possible': 62815, 'rule': 68967, 'fan': 28303, 'boll': 10464, 'enjoy': 26308, 'postal': 62821, 'maybe': 50752, 'apparently': 5117, 'buy': 12558, 'cry': 19407, 'long': 47919, 'ago': 2928, 'game': 31859, 'finsished': 29544, 'mercs': 51788, 'infiltrate': 40365, 'secret': 71162, 'research': 67115, 'labs': 45531, 'locate': 47725, 'tropical': 82682, 'island': 41590, 'warn': 87539, 'scheme': 70447, 'together': 81350, 'along': 3697, 'legion': 46569, 'schmucks': 70557, 'feel': 28809, 'loneley': 47904, 'invite': 41301, 'three': 80712, 'countrymen': 18602, 'players': 61960, 'name': 55116, 'til': 80975, 'schweiger': 70702, 'udo': 83443, 'kier': 44231, 'ralf': 65392, 'moeller': 53242, 'actually': 2277, 'selfs': 71371, 'biz': 9667, 'tale': 78958, 'jack': 41844, 'carver': 13731, 'yes': 90125, 'german': 32602, 'hail': 35399, 'bratwurst': 11264, 'dudes': 24428, 'however': 38448, 'tils': 80992, 'badass': 7165, 'complain': 17165, 'stay': 76228, 'true': 82758, 'whole': 88489, 'perspective': 60838, 'kick': 44170, 'beyond': 9184, 'demented': 21277, 'evil': 27309, 'mad': 48993, 'scientist': 70730, 'dr': 23978, 'krieger': 45146, 'genetically': 32420, 'mutate': 54761, 'soldier': 74597, 'gms': 33354, 'top': 81606, 'remind': 66768, 'spoiler': 75542, 'vancouver': 85782, 'reason': 65958, 'palm': 59361, 'tree': 82354, 'rich': 67670, 'lumberjack': 48483, 'woods': 89287, 'start': 76148, 'mehehe': 51460, 'bolls': 10475, 'shenanigans': 72341, 'deliver': 21196, 'mean': 51204, 'suck': 77479, 'imply': 39669, 'areas': 5446, 'boat': 10241, 'cromed': 19219, 'albino': 3327, 'squad': 75753, 'enter': 26410, 'reek': 66336, 'scheisse': 70437, 'poop': 62558, 'simpletons': 73260, 'fa': 27992, 'wiff': 88636, 'ahead': 3000, 'annoy': 4679, 'sidekick': 73018, 'shoot': 72663, 'minutes': 52718, 'screen': 70879, 'shakespeare': 72004, 'appreciate': 5212, 'mass': 50401, 'scottish': 70817, 'certain': 14355, 'rev': 67416, 'bowdler': 11012, 'hence': 36834, 'bowdlerization': 11014, 'victorian': 86418, 'era': 26671, 'improve': 39744, 'perfection': 60634, 'ten': 79776, 'text': 80081, 'english': 26271, 'composition': 17230, 'forte': 30559, 'keep': 43838, 'cut': 19732, 'fantastic': 28381, 'prisoners': 63567, 'famous': 28301, 'george': 32545, 'clooney': 16289, 'roll': 68359, 'man': 49617, 'constant': 17760, 'sorrow': 74928, 'recommand': 66123, 'everybody': 27271, 'greetings': 34348, 'bart': 7880, 'kind': 44361, 'draw': 24079, 'erotic': 26763, 'amateurish': 3897, 'unbelievable': 83772, 'bits': 9645, 'sort': 74932, 'school': 70597, 'project': 63796, 'rosanna': 68555, 'arquette': 5684, 'stock': 76618, 'bizarre': 9669, 'suppose': 77988, 'midwest': 52287, 'town': 81881, 'involve': 41311, 'lessons': 46843, 'learn': 46410, 'insights': 40715, 'stilted': 76547, 'quite': 65021, 'ridiculous': 67747, 'lot': 48115, 'skin': 73626, 'intrigue': 41179, 'videotape': 86463, 'nonsense': 56579, 'bisexual': 9607, 'relationship': 66644, 'nowhere': 56879, 'heterosexual': 37107, 'absurd': 1925, 'dance': 20133, 'stereotype': 76428, 'pass': 59889, 'million': 52493, 'miles': 52411, 'starve': 76158, 'aid': 3046, 'africa': 2784, 'simply': 73270, 'remake': 66725, 'fail': 28135, 'capture': 13356, 'flavor': 29866, 'terror': 79975, '1963': 603, 'title': 81202, 'liam': 46989, 'neeson': 55605, 'excellent': 27424, 'always': 3834, 'hold': 37732, 'exception': 27435, 'owen': 59041, 'wilson': 88785, 'luke': 48464, 'major': 49356, 'fault': 28643, 'version': 86256, 'stray': 76899, 'shirley': 72546, 'jackson': 41876, 'attempt': 6377, 'grandiose': 34095, 'thrill': 80734, 'earlier': 24932, 'trade': 81987, 'snazzier': 74256, 'special': 75233, 'effect': 25318, 'friction': 31084, 'older': 57779, 'horrible': 38204, 'continuous': 17915, 'minute': 52714, 'chance': 14527, 'development': 21958, 'busy': 12491, 'run': 69003, 'sword': 78485, 'emotional': 26018, 'attachment': 6363, 'except': 27433, 'machine': 48900, 'destroy': 21836, 'blatantly': 9877, 'steal': 76253, 'lotr': 48126, 'war': 87483, 'matrix': 50606, 'examples': 27401, 'ghost': 32753, 'final': 29445, 'yoda': 90192, 'obee': 57211, 'vader': 85609, 'spider': 75379, 'begin': 8531, 'frodo': 31194, 'attack': 6367, 'return': 67396, 'kings': 44410, 'elijah': 25699, 'wood': 89252, 'victim': 86404, 'wait': 87307, 'hypnotize': 38976, 'sting': 76560, 'wrap': 89540, 'uh': 83494, 'hello': 36754, 'vs': 87111, 'humans': 38667, 'terminator': 79922, 'someone': 74699, 'nazi': 55470, 'juvenile': 43175, 'rush': 69047, 'conclusion': 17365, 'adult': 2563, 'either': 25517, 'disappointment': 22669, 'save': 70124, 'remember': 66754, 'cinema': 15734, 'dark': 20284, 'nervous': 55781, '74': 1414, '75': 1421, 'dad': 19930, 'sister': 73448, 'newbury': 55899, 'berkshire': 8949, 'england': 26263, 'tigers': 80949, 'snow': 74360, 'appearance': 5130, 'grizzly': 34529, 'adams': 2323, 'actor': 2257, 'dan': 20127, 'haggery': 35361, 'anyone': 4946, 'dvd': 24763, 'etc': 27023, 'please': 62020, 'fitness': 29680, 'club': 16341, 'shame': 72061, 'nearest': 55515, '20': 699, 'hear': 36448, 'others': 58548, 'stinkers': 76578, 'nominate': 56502, 'golden': 33545, 'globe': 33277, 'female': 28911, 'renaissance': 66824, 'painter': 59266, 'mangle': 49714, 'recognition': 66105, 'complaint': 17170, 'liberties': 47028, 'facts': 28093, 'perfectly': 60639, 'fine': 29474, 'account': 2057, 'artist': 5829, 'dishwater': 22857, 'dull': 24507, 'script': 70926, 'enough': 26350, 'naked': 55094, 'factual': 28094, 'hurriedly': 38804, 'cap': 13260, 'summary': 77672, 'couple': 18615, 'hours': 38379, 'favor': 28667, 'brevity': 11460, 'sequels': 71616, 'surprise': 78099, '1990s': 650, 'glut': 33334, 'cash': 13764, 'wrong': 89609, 'guy': 35105, 'concept': 17318, 'cliffhanger': 16196, 'mountain': 54116, 'rescue': 67111, 'sly': 74036, 'stop': 76692, 'stallone': 75980, 'nit': 56343, 'pickers': 61402, 'especially': 26900, 'expert': 27680, 'climb': 16218, 'aviation': 6754, 'facial': 28056, 'expressions': 27785, 'full': 31376, 'excuse': 27505, 'dismiss': 22908, 'overblown': 58819, 'pile': 61536, 'junk': 43094, 'horse': 38243, 'lovable': 48215, 'undeniably': 83992, 'romp': 68450, 'plenty': 62054, 'unintentionally': 84556, 'john': 42705, 'lithgows': 47524, 'sneery': 74274, 'evilness': 27319, 'tick': 80899, 'box': 11043, 'baddies': 7179, 'permanently': 60722, 'harass': 35863, 'hapless': 35827, 'turncoat': 83092, 'agent': 2862, 'rex': 67544, 'linn': 47387, 'travers': 82292, 'henry': 36883, 'rooker': 68490, 'noteworthy': 56777, 'cringe': 19092, 'worthy': 89493, 'hal': 35463, 'insist': 40730, 'constantly': 17765, 'shriek': 72821, 'painful': 59253, 'disbelief': 22697, 'captors': 13355, 'hurt': 38812, 'anybody': 4935, 'whilst': 88351, 'surely': 78045, 'ralph': 65397, 'waite': 87308, 'frank': 30798, 'grin': 34474, 'girl': 33039, 'plummet': 62132, 'former': 30512, 'london': 47897, 'burn': 12364, 'craig': 18814, 'fairbrass': 28149, 'brit': 11626, 'cropper': 19250, 'football': 30322, 'help': 36781, 'judgement': 42969, 'lower': 48276, 'expectations': 27643, 'volume': 87012, 'qaulen': 64729, 'helicopter': 36717, 'terrible': 79952, 'misfortune': 52862, 'entirety': 26458, 'aspects': 6022, 'paper': 59534, 'thin': 80520, 'sequence': 71617, 'fake': 28184, 'pack': 59163, 'crappy': 18863, 'liners': 47355, 'respectable': 67219, 'amuse': 4174, 'gear': 32269, 'towards': 81875, 'women': 89215, 'utterly': 85543, 'unattractive': 83735, 'wrinkle': 89584, 'appear': 5129, 'weird': 87982, 'costume': 18483, 'miserably': 52846, 'absolutely': 1901, 'hrs': 38500, 'regret': 66493, 'rajnikanth': 65371, 'carry': 13674, 'shoulder': 72740, 'although': 3793, 'anything': 4952, 'music': 54694, 'rehman': 66535, 'straight': 76810, 'anime': 4570, 'matter': 50624, 'speed': 75297, 'racer': 65116, 'preschool': 63330, 'several': 71817, 'hilarious': 37306, 'godzilla': 33474, 'move': 54162, 'usual': 85489, 'fx': 31588, 'sudden': 77507, 'boom': 10678, 'wwwaaaaayyyyy': 89715, 'downhill': 23921, 'animation': 4561, 'worse': 89470, 'crissakes': 19134, 'vividly': 86887, 'bunch': 12239, 'dinosaurs': 22533, 'addition': 2359, 'transition': 82160, 'unorganized': 84768, 'dub': 24356, 'horrid': 38209, 'beg': 8517, 'tape': 79170, 'vhs': 86337, 'player': 61958, 'survive': 78140, 'crack': 18779, 'robots': 68167, 'joel': 42668, 'mike': 52351, 'mst3k': 54310, 'pick': 61395, 'season': 71095, 'honestly': 37988, 'barely': 7754, 'heck': 36548, 'plan': 61852, 'fellow': 28893, 'otaku': 58534, 'pal': 59296, 'mine': 52592, 'halloween': 35543, 'night': 56159, 'stupid': 77173, 'improvement': 39745, 'originally': 58354, 'accord': 2048, 'grade': 34007, 'scale': 70226, 'count': 18562, 'unless': 84647, 'worldfest': 89439, 'receive': 66047, 'amount': 4117, 'applause': 5164, 'afterwards': 2824, 'beals': 8246, 'parker': 59727, 'actress': 2267, 'part': 59795, 'allow': 3609, 'judge': 42967, 'unsympathetic': 85117, 'therefore': 80389, 'depth': 21582, 'revolve': 67519, 'cop': 18128, 'video': 86435, '90s': 1528, 'standards': 76005, 'karen': 43527, 'carpenter': 13617, 'singer': 73333, 'complex': 17193, 'though': 80669, 'accurate': 2076, 'detail': 21855, 'cynthia': 19849, 'gibb': 32818, 'portray': 62744, 'election': 25602, 'naive': 55074, 'dumb': 24529, 'role': 68347, 'stronger': 77040, 'personality': 60813, 'louise': 48172, 'fletcher': 29926, 'agnes': 2919, 'terrific': 79960, 'job': 42624, 'songs': 74778, 'album': 3336, 'unfortunately': 84377, 'ratings': 65673, 'usa': 85439, 'countries': 18597, 'cell': 14215, 'exotic': 27616, 'masterpiece': 50459, 'dizzy': 23228, 'trip': 82557, 'vast': 85929, 'mind': 52563, 'conclusive': 17368, 'evidence': 27301, 'achieve': 2113, 'beings': 8592, 'unleash': 84645, 'uninhibited': 84532, 'imaginations': 39436, 'boldness': 10444, 'push': 64588, 'aside': 5985, 'thoughts': 80682, 'formulas': 30526, 'cliches': 16174, 'create': 18940, 'magnificent': 49189, 'numerous': 57013, 'complaints': 1717

<h2>Problem- 5</h2>

<h5>bi-gram</h5
               >

In [12]:
n_grams=CountVectorizer(ngram_range=(2,2))

In [13]:
ng=n_grams.fit_transform(df['review'])

In [17]:
print("Bigram vocabulary size:", len(n_grams.vocabulary_))

Bigram vocabulary size: 2740881

<h5>tri-gram</h5>

In [15]:
n_grams2=CountVectorizer(ngram_range=(3,3))
ng2=n_grams2.fit_transform(df['review'])

In [18]:
print("Trigram vocabulary size:", len(n_grams2.vocabulary_))

Trigram vocabulary size: 5311757

<p>Observation: The vocabulary dimensionality increases significantly as the value of N increases. The bigram vocabulary contains 2,740,881 unique combinations, while the trigram vocabulary contains 5,311,757 unique combinations. Thus, higher-order n-grams result in higher dimensionality because they generate more unique word combinations.</p>

<h2>Problem- 6</h2>

<h5>Tf-Idf</h5>

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv=TfidfVectorizer()

In [21]:
tfidf=tfidfv.fit_transform(df['review'])

In [22]:
print("TfIdf vocabulary size:", len(tfidfv.vocabulary_))

TfIdf vocabulary size: 91071

In [23]:
#IDF SCORE DATAFRAME
idf_df=pd.DataFrame({
    'word':tfidfv.get_feature_names_out(),
    'idf_val':tfidfv.idf_
})

In [24]:
idf_df.head()

            word    idf_val
0             00   6.638015
1            000   5.703906
2    00000000000  11.126651
3  0000000000001  11.126651
4       00000001  11.126651